[package]
name = "zecwallet-cli"
version = "2.0.0"
edition = "2021"

[dependencies]
rustyline = "9"
clap = "3"
log = "0.4"
shellwords = "1"
json = "0.12"
http = "0.2"

zecwalletlitelib = { path = "../lib/" }
