[package]
name = "zecwallet-cli"
version = "1.8.0"
edition = "2018"

[dependencies]
rustyline = "5.0.6"
clap = "2.33"
log = "0.4"
shellwords = "1.0.0"
json = "0.12.0"
http = "0.2"

zecwalletlitelib = { path = "../lib/" }
