name: Rust

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Install system dependencies
        run: apt-get update && apt-get install -y libudev-dev

      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.66
          override: true
          components: rustfmt, clippy
      # - name: cargo fetch
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: fetch
      - name: Build 
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all
